[package]
name = "wget"
version = "0.1.0"
edition = "2024"

[dependencies]
daemonize = "0.5.0"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
url = "2.5.7"

