[package]
name = "wget"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3"
clap = "4.5.46"
reqwest = { version = "0.12", features = ["json", "stream", "blocking"] }
tokio = { version = "1", features = ["full"] }
url = "2.5.7"
anyhow = "1.0.99"
regex = "1.11.2"

